/* Generated file, do not edit! */

#include "impulse.fp.h"

char const* const impulse_fp = 
   "uniform samplerRECT positions;\n"
   "uniform samplerRECT velocities;\n"
   "uniform float3 impulsePosition;\n"
   "uniform float impulseRadius;\n"
   "uniform float impulseStrength;\n"
   "void main (\n"
   "	in 		float2 texID : WPOS,\n"
   "	out 	float3 newVelocity : COLOR0\n"
   "){\n"
   "	float3 position =(float3) texRECT (positionTexture, texID);\n"
   "	float3 velocity = texRECT (velocityTexture, texID);\n"
   "	\n"
   "	float distance = distance(position, impulsePosition);\n"
   "	if(distance > radius){\n"
   "		newVelocity = velocity;\n"
   "	}\n"
   "	\n"
   "	float myScale = 1 - distance / radius;\n"
   "	\n"
   "	float3 myDirection = impulsePosition - position;\n"
   "	normalize(myDirection);\n"
   "	myDirection *= myScale;\n"
   "	myDirection *= impulseStrength;\n"
   "	\n"
   "	newVelocity = myDirection;\n"
   "	\n"
   "}\n"
   "	           \n"
   ;
