/* Generated file, do not edit! */

#include "impulses.fp.h"

char const* const impulses_fp = 
   "interface Impulse{\n"
   "	float3 impulse(float3 thePosition, float3 theVelocity, float2 theTexID, float theDeltaTime);\n"
   "};\n"
   "struct SphereImpulse : Impulse{\n"
   "	float3 center;\n"
   "	float radius;\n"
   "	float strength;\n"
   "	float3 impulse(float3 thePosition, float3 theVelocity, float2 theTexID, float theDeltaTime){\n"
   "	\n"
   "		float dist = distance(center, thePosition);\n"
   "		\n"
   "		if(dist > radius){\n"
   "			return float3(0);\n"
   "		}\n"
   "	\n"
   "		float myScale = 1 - dist / radius;\n"
   "	\n"
   "		float3 myDirection = thePosition - center;\n"
   "		normalize(myDirection);\n"
   "		myDirection *= myScale;\n"
   "		myDirection *= strength;\n"
   "		return myDirection;\n"
   "	}\n"
   "};\n"
   "uniform Impulse impulses[];\n"
   ;
