/* Generated file, do not edit! */

#include "nearestTarget.fp.h"

char const* const nearestTarget_fp = 
   "// texture holding the grid and storing which position is taken and which not\n"
   "uniform samplerRECT targets;\n"
   "// texture holding the target at avery particle xyid and the duration after\n"
   "// which the target is applied\n"
   "uniform samplerRECT particleTargetInfos;\n"
   "uniform samplerRECT particlePositions;\n"
   "uniform samplerRECT particleInfos;\n"
   "uniform samplerRECT particleVelocities;\n"
   "uniform sampler2D mask;\n"
   "uniform float2 textureSize;\n"
   "uniform float2 textureScale;\n"
   "uniform float2 textureOffset;\n"
   "uniform float deltaTime;\n"
   "uniform float lookAhead;\n"
   "uniform float targetTime;\n"
   "uniform bool useMask;\n"
   "float4 main(\n"
   "	in float2 wPos : WPOS,\n"
   "	out float4 oColor2 : COLOR1\n"
   ") : COLOR0{\n"
   "	float4 particleTargetInfo = texRECT(particleTargetInfos, wPos);\n"
   "	float4 particleInfo = texRECT(particleInfos, wPos);\n"
   "	\n"
   "	// particle is dead delete target\n"
   "	if(particleInfo.x >= particleInfo.y || particleInfo.x == 0){\n"
   "		return float4(0,0,0,0);\n"
   "	}\n"
   "	\n"
   "	// particle has target and is alive just leave everything as it is\n"
   "	if(particleTargetInfo.z > 0){\n"
   "		if(particleTargetInfo.z > targetTime){\n"
   "			return float4(0,0,particleTargetInfo.z,0);\n"
   "		} else {\n"
   "			return float4(particleTargetInfo.xy,particleTargetInfo.z + deltaTime,1);\n"
   "		}\n"
   "	}\n"
   "	\n"
   "	\n"
   "	// if particles target time is not reached discard \n"
   "	//if(particleInfo.x < particleTargetInfo.w)use = 0;\n"
   "	\n"
   "	float3 particlePosition = texRECT(particlePositions, wPos);\n"
   "	float3 particleVelocity = texRECT(particleVelocities, wPos);\n"
   "	\n"
   "	float2 texturePos = particlePosition.xy + particleVelocity.xy * lookAhead;\n"
   "	texturePos = ((texturePos * float2(1,1)) - textureOffset)  / textureScale;\n"
   "	texturePos = floor(texturePos);\n"
   "	\n"
   "	// particle is outside grid so discard\n"
   "	if(texturePos.x < 0 || texturePos.y < 0 || texturePos.x >= textureSize.x || texturePos.y >= textureSize.y){\n"
   "		return float4(1,0,0,0);\n"
   "	}\n"
   "	\n"
   "	\n"
   "	float4 targetInfo = texRECT(targets, texturePos.xy);\n"
   "	\n"
   "	if(useMask){\n"
   "		float2 texCoord = texturePos.xy / textureSize;\n"
   "		float4 maskColor = tex2D(mask, float2(texCoord.x, texCoord.y));\n"
   "		if(!maskColor.x)return float4(3,0,0,0);\n"
   "	}\n"
   "	\n"
   "	// target is taken so discard\n"
   "	if(targetInfo.z > 0){\n"
   "		return float4(2,0,0,0);\n"
   "	}\n"
   "	\n"
   "	return float4(texturePos.xy,deltaTime,1);\n"
   "	\n"
   "}\n"
   ;
