/* Generated file, do not edit! */

#include "velocity.fp.h"

char const* const velocity_fp = 
   "uniform float deltaTime;\n"
   "uniform samplerRECT colorTexture;\n"
   "void main (\n"
   "	in 	float2 texID : WPOS,\n"
   "	out float4 newPosition : COLOR0,\n"
   "	out float4 newInfo : COLOR1,\n"
   "	out float3 newVelocity : COLOR2,\n"
   "	out float4 newColor : COLOR3\n"
   "){\n"
   "	float3 position =(float3) texRECT (positionTexture, texID);\n"
   "	float3 velocity = texRECT (velocityTexture, texID);\n"
   "	float4 color = texRECT (colorTexture, texID);\n"
   "	float3 acceleration = float3(0,0,0);\n"
   "	\n"
   "	for(int i = 0; i < forces.length;i++){\n"
   "		acceleration = acceleration + forces[i].force(position,velocity,texID,deltaTime);\n"
   "	}\n"
   "	\n"
   "	velocity = velocity + acceleration * (deltaTime * 60);\n"
   "	\n"
   "	for(int i = 0; i < constraints.length;i++){\n"
   "		velocity = constraints[i].constraint(velocity, position,texID, deltaTime);\n"
   "	}\n"
   "	\n"
   "	for(int i = 0; i < impulses.length;i++){\n"
   "		velocity += impulses[i].impulse(position,velocity, texID, deltaTime);\n"
   "	}\n"
   "	newVelocity = velocity;\n"
   "	\n"
   "	float4 lastInfo = texRECT(infoTexture, texID);\n"
   "	float myAge = lastInfo.x;\n"
   "	int myStep = (int)lastInfo.w;\n"
   "	\n"
   "	newInfo = float4(\n"
   "		lastInfo.x + deltaTime,\n"
   "		lastInfo.y,\n"
   "		lastInfo.z,\n"
   "		lastInfo.w\n"
   "	);\n"
   "	\n"
   "	newColor = color;\n"
   "	\n"
   "	if(myAge >= lastInfo.y && lastInfo.z == 0.0)position = float3(1000000,0,0);\n"
   "	newPosition = float4(position + deltaTime * velocity,1); \n"
   "}\n"
   "	           \n"
   ;
