/* Generated file, do not edit! */

#include "gbuffer_emit.fp.h"

char const* const gbuffer_emit_fp = 
   "uniform samplerRECT positionTexture;\n"
   "uniform samplerRECT velocityTexture;\n"
   "uniform samplerRECT infoTexture;\n"
   "uniform samplerRECT colorTexture;\n"
   "uniform sampler2D geometryTexture;\n"
   "uniform sampler2D geometryColorTexture;\n"
   "uniform float deltaTime;\n"
   "uniform float2 gBufferSize;\n"
   "uniform float3 randomSeed;\n"
   "uniform float emitProb;\n"
   "uniform float4x4 inverseView;\n"
   "float rand(float2 n){\n"
   "  return fract(sin(dot(n.xy, randomSeed.xy))* randomSeed.z);\n"
   "}\n"
   "void main (\n"
   "	in 	float2 texID : WPOS,\n"
   "	out float4 newPosition : COLOR0,\n"
   "	out float4 newInfo : COLOR1,\n"
   "	out float3 newVelocity : COLOR2,\n"
   "	out float4 newColor : COLOR3\n"
   "){\n"
   "	//float3 position = mul(inverseView, texRECT (positionTexture, texID));\n"
   "	float3 position =  texRECT (positionTexture, texID);\n"
   "	float4 velocity = texRECT (velocityTexture, texID);\n"
   "	\n"
   "	newVelocity = velocity;\n"
   "	newColor = texRECT (colorTexture, texID);\n"
   "	\n"
   "	newInfo = texRECT(infoTexture, texID);\n"
   "	float myAge = newInfo.x;\n"
   "	\n"
   "	if(myAge >= newInfo.y && newInfo.z == 0.0){\n"
   "		position = float3(1000000,0,0);\n"
   "		\n"
   "		if(rand(texID) < emitProb){\n"
   "			float2 myTexCoord = float2(rand(texID + float2(3000,0)),rand(texID + float2(4000,0)));\n"
   "			float4 gBufferPosition = tex2D(geometryTexture,myTexCoord);\n"
   "			float4 gBufferColor = tex2D(geometryColorTexture,myTexCoord);\n"
   "			if(length(gBufferPosition) > 1){\n"
   "				position = gBufferPosition;\n"
   "				newInfo.x = 0;\n"
   "				newInfo.y = 10;\n"
   "				newInfo.z = 0;\n"
   "				newVelocity = float3(0,0,0);\n"
   "				newColor = gBufferColor;\n"
   "			}\n"
   "		}\n"
   "	}\n"
   "	\n"
   "	//float2 myTexCoord = float2(rand(texID + float2(3000,0)),rand(texID + float2(4000,0)));\n"
   "	//position = tex2D(geometryTexture,myTexCoord);\n"
   "	newPosition = float4(position,1); \n"
   "}\n"
   ;
