/* Generated file, do not edit! */

#include "simple_shader_emit.fp.h"

char const* const simple_shader_emit_fp = 
   "uniform samplerRECT positionTexture;\n"
   "uniform samplerRECT velocityTexture;\n"
   "uniform samplerRECT infoTexture;\n"
   "uniform float deltaTime;\n"
   "uniform float3 randomSeed;\n"
   "uniform float emitProb;\n"
   "float rand(float2 n){\n"
   "  return fract(sin(dot(n.xy, randomSeed.xy))* randomSeed.z);\n"
   "}\n"
   "void main (\n"
   "	in 	float2 texID : WPOS,\n"
   "	out float4 newPosition : COLOR0,\n"
   "	out float4 newInfo : COLOR1,\n"
   "	out float3 newVelocity : COLOR2 \n"
   "){\n"
   "	float3 position = (float3)texRECT (positionTexture, texID);\n"
   "	float4 velocity = texRECT (velocityTexture, texID);\n"
   "	\n"
   "	newVelocity = velocity;\n"
   "	\n"
   "	float4 lastInfo = texRECT(infoTexture, texID);\n"
   "	float myAge = lastInfo.x;\n"
   "	\n"
   "	newInfo =lastInfo;\n"
   "	\n"
   "	if(lastInfo.x >= lastInfo.y && lastInfo.z == 0.0){\n"
   "		position = float3(1000000,0,0);\n"
   "		\n"
   "		if(rand(texID) < emitProb){\n"
   "			position = float3(rand(texID + float2(3000,0)) * 2 - 1,rand(texID + float2(4000,0)) * 2 - 1, 0);\n"
   "			position *= 300;\n"
   "			newInfo.x = 0;\n"
   "			newInfo.y = 10;\n"
   "			newInfo.z = 0;\n"
   "			newVelocity = float3(rand(texID + float2(1000,0)) * 2 - 1,rand(texID + float2(2000,0)) * 2 - 1, 0);\n"
   "			newVelocity *= 10;\n"
   "		}\n"
   "	}\n"
   "	newPosition = float4(position,1); \n"
   "}\n"
   "	           \n"
   ;
